default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: clothing_store_dev

test:
  <<: *default
  database: clothing_store_test

production:
  <<: *default
  database: clothing_store_production
  username: store
  password: <%= ENV['CLOTHING_DATABASE_PASSWORD'] %>
