# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2aae112cbd9bda9d6f32411e8f9b71335b5398ee56167e184a20a6a99e48086e4b82a980d82f985b1ffd65cf974eee828439719d3e9cff807662efdd2856145

test:
  secret_key_base: 3fc3dd652a9676fd9624105fc6ea72f30daf4c5238d040e79add3218b9bfce3ba9a804dfedbe51f8b3001f1b26dfcdc6ef35173eefcb5033103b5d2279a8e6de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
